Onyx-Protocol/onyx-interface

src/clients/api/mutations/borrowOToken/index.ts, src/utilities/RPCErrorMessage.ts, src/utilities/index.ts
=> add error handling for borrowing

src/pages/Swap/useGetSwapInfo/formatToSwap.ts
=> fix wrong swap amount

src/pages/History/Filters/index.tsx, src/pages/History/HistoryTable/index.tsx, src/translation/translations/en.json
=> feat: asset field

src/pages/History/Filters/index.tsx, src/pages/History/index.tsx
=> fixes: pagination, filter

src/clients/api/queries/getOwnedPunkIds/useGetOwnedPunkIds.ts, src/clients/api/queries/getOwnedWPunksIds/useGetOwnedWPunksIds.ts, src/clients/api/queries/getProxies/useGetProxies.ts
=> rm object type

src/pages/Stake/Modals/ActionModal/index.tsx, src/pages/Stake/TransactionForm/index.tsx, src/pages/Stake/TransactionForm/styles.ts
- Compare allowance and amount inside ActionModal, and show `Enable` button if allowance is less than amount.
=> Hotfix/bug staking doesnt work#10

src/pages/Stake/Modals/ActionModal/index.tsx, src/pages/Stake/Modals/StakeModal/index.tsx, src/pages/Stake/TransactionForm/index.tsx, src/translation/translations/en.json
- Updated increase allowance warning and button labels
=> updated increase allowance warning and button labels

src/pages/History/index.tsx
=> feat: auto refresh

src/clients/api/queries/getProposals/useGetProposal.ts, src/clients/api/queries/getProposals/useGetProposals.ts
=> feature auto refresh proposals

src/clients/api/queries/getProposals/useGetProposal.ts
=> fix build error

src/utilities/getVoterHistorySubGraph.ts
=> fix sorting in voter history

src/translation/translations/en.json
=> fix locale

src/pages/Proposal/VoteSummary/index.tsx, src/pages/Proposal/VoteSummary/styles.ts
=> feat: icon for zero vote

src/components/Layout/Sidebar/index.tsx
=> fix remove scroll

src/components/Layout/Footer/index.tsx, src/components/Layout/Footer/styles.ts, src/components/Layout/Header/index.tsx, src/components/Layout/Header/styles.ts
=> move to footer

src/components/Layout/Footer/index.tsx, src/components/Layout/Footer/styles.ts
=> move to right side

src/components/Modal/index.tsx, src/pages/App.tsx
=> warning popup

src/pages/App.tsx
=> understand button

src/constants/enabled.ts, src/pages/App.tsx, src/pages/Dashboard/Markets/BorrowMarket/index.tsx, src/pages/Dashboard/Markets/SupplyMarket/index.tsx
=> restrict supply & borrow

src/constants/enabled.ts, src/pages/App.tsx, src/pages/Dashboard/Markets/BorrowMarket/index.tsx, src/pages/Dashboard/Markets/SupplyMarket/index.tsx
=> enable supply & borrow for XCN

src/components/Layout/constants.tsx, src/constants/path.ts, src/pages/App.tsx, src/pages/History/Filters/index.tsx
- Hide and remove these menus
Dashboard
Markets
XCN
Liquidate
Punk Wrapper
=> hide links

src/clients/web3/useAuth/index.ts, src/clients/web3/walletDetectionUtils.ts, src/components/Layout/AddNetworkButton/addOnyx2Network.ts, src/components/Layout/Sidebar/index.tsx
This code was leftover from the debug for wallet connectivity not working in onyx wallet, and was causing performance issues due to the timeout on the very first render of the app.
Also not rendering the `Add Onyx chain` button on mobile sidebar anymore, it's missleading because user is already on that chain (it was confusing me)
=> fix(performance-issue): remove unnecesery wallet detection logic
